labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Here you can propose an idea how to improve a current feature or an idea for a brand new feature.

  - type: textarea
    id: problem
    attributes:
      label: Describe the Problem
      description: |
        Write a concise description of what the problem is with your use case.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the Solution
      description: |
        Write a concise description of the solution to the problem described above (i.e., how the feature should work).
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe the Alternative Solutions
      description: |
        Write a concise description of any alternative solutions or features you've considered to solve the problem described above.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Information
      description: Add any additional information, screenshots, or videos you think are useful.
